### ISSUE TITLE
KeyError: 'execution'

### ISSUE THREAD

**Issue by PenguinRage** [Beuth-Erdelt/DBMS-Benchmarker#80]
Upon running the benchmark example query. I encountered this error. One work around was just removing it altogether.

```
Traceback (most recent call last):
  File "/Users/iancleasby/Repos/Github/DBMS-Benchmarker/benchmark.py", line 180, in <module>
    evaluator.evaluator(experiments, load=False, force=True)
  File "/Users/iancleasby/Repos/Github/DBMS-Benchmarker/dbmsbenchmarker/evaluator.py", line 58, in __init__
    evaluator.evaluation = self.generate()
  File "/Users/iancleasby/Repos/Github/DBMS-Benchmarker/dbmsbenchmarker/evaluator.py", line 123, in generate
    times = findTimesOfSuccessfulQueries()
  File "/Users/iancleasby/Repos/Github/DBMS-Benchmarker/dbmsbenchmarker/evaluator.py", line 110, in findTimesOfSuccessfulQueries
    qs = tools.findSuccessfulQueriesAllDBMS(self.benchmarker, None, self.benchmarker.timers)[e[0]]
  File "/Users/iancleasby/Repos/Github/DBMS-Benchmarker/dbmsbenchmarker/tools.py", line 1321, in findSuccessfulQueriesAllDBMS
    if not queryObject.timer[t.name]['active']:
KeyError: 'execution'
```

**Comment by perdelt** [comment]
This indicates that there has not been any successful query at all. Can you confirm this?

**Comment by perdelt** [comment]
This exception is caught in v0.11.16. However, it remains a problem if no query is successful.
